version: "3"

services: 
  db:
    image: "mongo"
    volumes: 
      - ~/docker/databases/mongodata:/data/db
    ports:
      - 27017:27017
    logging: 
      driver: none
  server:
    build: .
    depends_on:
      - db
    ports: 
      - ${PORT}:${PORT}
    links: 
      - db
    env_file:
      - .env
